### PRODUCTS ROUTE

### GET ALL PRODUCTS
GET http://localhost:3000/products

### GET SINGLE PRODUCT
GET http://localhost:3000/products/1

### CREATE NEW PRODUCT
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Sofra",
    "price": 1500,
    "category": "Living Room"
}

### GET BY CATEGORY
GET http://localhost:3000/products/category/Living%20Room


### USERS ROUTE

### GET ALL USERS
GET http://localhost:3000/users

### GET SINGLE USER
GET http://localhost:3000/users/2

### CREATE NEW USER
POST http://localhost:3000/users
Content-Type: application/json

{
    "first_name": "David",
    "last_name": "Lawrence",
    "password": "secret"
}

### AUTHENTICATE USER
POST http://localhost:3000/users/auth
Content-Type: application/json

{
    "first_name": "David",
    "last_name": "Lawrence",
    "password": "secret"
}