### PRODUCTS ROUTE

### GET ALL PRODUCTS
GET http://localhost:3000/products

### GET SINGLE PRODUCT
GET http://localhost:3000/products/1

### CREATE NEW PRODUCT
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Sofra",
    "price": 1500,
    "category": "Living Room"
}

### GET BY CATEGORY
GET http://localhost:3000/products/category/Living%20Room


### USERS ROUTE

### GET ALL USERS
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiJDJiJDEwJE1LY2NUaVRhQ2tXWlRNQnBSejJhcXVqSGw5VlBBY1U0VXJuLlpBWW1wRy5DZDExUjc0MHdLIiwiaWF0IjoxNjQ0MDgzMjQwLCJleHAiOjE2NDQwODUwNDB9.JcMjU_SW4N5qtBDMnTGz6q48x5ywssgpTVynYyDmer0

### GET SINGLE USER
GET http://localhost:3000/users/2

### CREATE NEW USER
POST http://localhost:3000/users
Content-Type: application/json

{
    "first_name": "David",
    "last_name": "Lawrence",
    "password": "secret"
}

### CREATE NEW USER 2
POST http://localhost:3000/users
Content-Type: application/json

{
    "first_name": "Helen",
    "last_name": "Pierce",
    "password": "nothere"
}

### AUTHENTICATE USER
POST http://localhost:3000/users/auth
Content-Type: application/json

{
    "first_name": "David",
    "last_name": "Lawrence",
    "password": "secret"
}

### ORDERS ROUTE

### GET ORDER BY USER
GET http://localhost:3000/orders/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiJDJiJDEwJHBWVWFqeW1VNnhtUC9WaGdvNVM4bWVldnouWGoyRW1pbnBidWNuWkVsSTFwTlpRNXVXdXJhIiwiaWF0IjoxNjQ0MDg2ODExLCJleHAiOjE2NDQwODg2MTF9.gEX_hvAgGDiOIxyDeYUYwnjxmRB-FsNvh5EbV9JQZdY

### GET COMPLETED BY USER
GET http://localhost:3000/orders/completed/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiJDJiJDEwJE1LY2NUaVRhQ2tXWlRNQnBSejJhcXVqSGw5VlBBY1U0VXJuLlpBWW1wRy5DZDExUjc0MHdLIiwiaWF0IjoxNjQ0MDgzMjQwLCJleHAiOjE2NDQwODUwNDB9.JcMjU_SW4N5qtBDMnTGz6q48x5ywssgpTVynYyDmer0

