### PRODUCTS ROUTE

### GET ALL PRODUCTS
GET http://localhost:3000/products

### GET SINGLE PRODUCT
GET http://localhost:3000/products/1

### CREATE NEW PRODUCT
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdF9uYW1lIjoiRGF2aWQiLCJsYXN0X25hbWUiOiJMYXdyZW5jZSIsInBhc3N3b3JkIjoiJDJiJDEwJDFNM21DLlhIZVhRNllzbEVTamJyTWV0UGJHZml3ek5PYUxqZGouY2U3UHlGR3d2ZkJuaHdLIn0sImlhdCI6MTY0NDMyNzcyOSwiZXhwIjoxNjQ0MzI5NTI5fQ.QFOwRHM_CYrTLakdj6UM6j38WV_2mi9GkkUkIN0mnzg

{
    "name": "Sofra",
    "price": 1500,
    "category": "Living Room"
}

### GET BY CATEGORY
GET http://localhost:3000/products/category/Living%20Room


### USERS ROUTE

### GET ALL USERS
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdF9uYW1lIjoiRGF2aWQiLCJsYXN0X25hbWUiOiJMYXdyZW5jZSIsInBhc3N3b3JkIjoiJDJiJDEwJDFNM21DLlhIZVhRNllzbEVTamJyTWV0UGJHZml3ek5PYUxqZGouY2U3UHlGR3d2ZkJuaHdLIn0sImlhdCI6MTY0NDMyNzcyOSwiZXhwIjoxNjQ0MzI5NTI5fQ.QFOwRHM_CYrTLakdj6UM6j38WV_2mi9GkkUkIN0mnzg

### GET SINGLE USER
GET http://localhost:3000/users/2

### CREATE NEW USER
POST http://localhost:3000/users
Content-Type: application/json

{
    "first_name": "David",
    "last_name": "Lawrence",
    "password": "secret"
}

### CREATE NEW USER 2
POST http://localhost:3000/users
Content-Type: application/json

{
    "first_name": "Helen",
    "last_name": "Pierce",
    "password": "nothere"
}

### AUTHENTICATE USER
POST http://localhost:3000/users/auth
Content-Type: application/json

{
    "first_name": "David",
    "last_name": "Lawrence",
    "password": "secret"
}

### ORDERS ROUTE

### CREATE NEW ORDER
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdF9uYW1lIjoiRGF2aWQiLCJsYXN0X25hbWUiOiJMYXdyZW5jZSIsInBhc3N3b3JkIjoiJDJiJDEwJDhUOVpHai9PazVkTnpwb0tJT0xKbXVSVWwwekJHcnMzOFphVFNEbWtJUmFUZ05YRHBHb2x5In0sImlhdCI6MTY0NDQwMDMzNywiZXhwIjoxNjQ0NDAyMTM3fQ.FFEO4YGXHbc1wSfM8DLTO_X-vV2yDMa5CeviPKQ2Dks

{
    "user_id": 1
}

### GET ORDER BY USER
GET http://localhost:3000/orders/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdF9uYW1lIjoiRGF2aWQiLCJsYXN0X25hbWUiOiJMYXdyZW5jZSIsInBhc3N3b3JkIjoiJDJiJDEwJDFNM21DLlhIZVhRNllzbEVTamJyTWV0UGJHZml3ek5PYUxqZGouY2U3UHlGR3d2ZkJuaHdLIn0sImlhdCI6MTY0NDMyNzcyOSwiZXhwIjoxNjQ0MzI5NTI5fQ.QFOwRHM_CYrTLakdj6UM6j38WV_2mi9GkkUkIN0mnzg

### GET COMPLETED BY USER
GET http://localhost:3000/orders/completed/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdF9uYW1lIjoiRGF2aWQiLCJsYXN0X25hbWUiOiJMYXdyZW5jZSIsInBhc3N3b3JkIjoiJDJiJDEwJDFNM21DLlhIZVhRNllzbEVTamJyTWV0UGJHZml3ek5PYUxqZGouY2U3UHlGR3d2ZkJuaHdLIn0sImlhdCI6MTY0NDMyNzcyOSwiZXhwIjoxNjQ0MzI5NTI5fQ.QFOwRHM_CYrTLakdj6UM6j38WV_2mi9GkkUkIN0mnzg

